# Generated by Django 3.2 on 2025-03-31 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
        ('individuals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='num_genera',
            field=models.IntegerField(default=0, editable=False, verbose_name='# categories'),
        ),
        migrations.AlterField(
            model_name='individual',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.plant', verbose_name='Plant'),
        ),
        migrations.AlterField(
            model_name='territory',
            name='num_genera',
            field=models.IntegerField(default=0, editable=False, verbose_name='# categories'),
        ),
    ]
