# Generated by Django 3.2 on 2025-03-22 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0002_auto_20250318_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual',
            old_name='species',
            new_name='plant',
        ),
    ]
