# Generated by Django 3.2 on 2025-03-18 22:05

import config_tables.admin
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0002_alter_species_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ('category__genus', 'species', 'subspecies'), 'permissions': (('can_check_nomenclature', 'can check nomenclature of a species'),), 'verbose_name': 'species', 'verbose_name_plural': 'species'},
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='category')),
                ('subfamily', models.CharField(blank=True, max_length=50, verbose_name='subfamily')),
                ('tribus', models.CharField(blank=True, max_length=50, verbose_name='tribus')),
                ('subtribus', models.CharField(blank=True, max_length=50, verbose_name='subtribus')),
                ('genus', models.CharField(max_length=50, verbose_name='genus')),
                ('genus_author', models.CharField(blank=True, max_length=100, verbose_name='author')),
                ('full_name_generated', models.CharField(blank=True, max_length=350, verbose_name='full name')),
            ],
            options={
                'verbose_name': 'genus',
                'verbose_name_plural': 'genera',
                'ordering': ('genus', 'category'),
                'unique_together': {('category', 'subfamily', 'tribus', 'subtribus', 'genus', 'genus_author')},
            },
            bases=(models.Model, config_tables.admin.Configurable),
        ),
        migrations.AddField(
            model_name='species',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='species.category', verbose_name='genus & category'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='species',
            unique_together={('category', 'species', 'species_author', 'subspecies', 'variety', 'form', 'cultivar', 'deutscher_name')},
        ),
        migrations.RemoveField(
            model_name='species',
            name='family',
        ),
        migrations.DeleteModel(
            name='Family',
        ),
    ]
