# Generated by Django 3.2 on 2025-03-18 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0003_auto_20250318_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='species.category', verbose_name='genus & category'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('category', 'tribus', 'subtribus', 'genus', 'genus_author')},
        ),
        migrations.RemoveField(
            model_name='category',
            name='subfamily',
        ),
    ]
