# Generated by Django 3.2 on 2025-03-19 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0004_auto_20250318_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='species.category', verbose_name='genus & category'),
        ),
    ]
