# Generated by Django 3.2 on 2025-03-20 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0005_alter_species_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='area_of_distribution_background',
        ),
        migrations.RemoveField(
            model_name='species',
            name='area_of_distribution_etikettxt',
        ),
        migrations.AlterField(
            model_name='species',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='species.category', verbose_name='genus & category'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('category', 'genus')},
        ),
        migrations.RemoveField(
            model_name='category',
            name='genus_author',
        ),
        migrations.RemoveField(
            model_name='category',
            name='subtribus',
        ),
        migrations.RemoveField(
            model_name='category',
            name='tribus',
        ),
    ]
