# Generated by Django 3.2 on 2025-03-22 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0006_auto_20250320_2324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('category',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ('category__category', 'species', 'subspecies'), 'permissions': (('can_check_nomenclature', 'can check nomenclature of a species'),), 'verbose_name': 'species', 'verbose_name_plural': 'species'},
        ),
        migrations.AlterField(
            model_name='species',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='species.category', verbose_name='category'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='category',
            name='full_name_generated',
        ),
        migrations.RemoveField(
            model_name='category',
            name='genus',
        ),
    ]
