# Generated by Django 3.2 on 2025-03-22 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0007_auto_20250322_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='full_name_generated',
            field=models.CharField(blank=True, max_length=350, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='species',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='species.category', verbose_name='category'),
        ),
    ]
