# Generated by Django 3.2 on 2025-03-22 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0008_auto_20250322_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ('category__category', 'collective_species', 'species'), 'permissions': (('can_check_nomenclature', 'can check nomenclature of a species'),), 'verbose_name': 'species', 'verbose_name_plural': 'species'},
        ),
        migrations.AddField(
            model_name='species',
            name='collective_species',
            field=models.CharField(blank=True, max_length=100, verbose_name='collective_species'),
        ),
        migrations.AlterField(
            model_name='species',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='species.category', verbose_name='category'),
        ),
        migrations.AlterUniqueTogether(
            name='species',
            unique_together={('category', 'collective_species', 'species', 'cultivar')},
        ),
        migrations.RemoveField(
            model_name='species',
            name='deutscher_name',
        ),
        migrations.RemoveField(
            model_name='species',
            name='form',
        ),
        migrations.RemoveField(
            model_name='species',
            name='form_author',
        ),
        migrations.RemoveField(
            model_name='species',
            name='lifeform',
        ),
        migrations.RemoveField(
            model_name='species',
            name='nomenclature_checked',
        ),
        migrations.RemoveField(
            model_name='species',
            name='poisonous_plant',
        ),
        migrations.RemoveField(
            model_name='species',
            name='protection_of_species',
        ),
        migrations.RemoveField(
            model_name='species',
            name='species_author',
        ),
        migrations.RemoveField(
            model_name='species',
            name='subspecies',
        ),
        migrations.RemoveField(
            model_name='species',
            name='subspecies_author',
        ),
        migrations.RemoveField(
            model_name='species',
            name='variety',
        ),
        migrations.RemoveField(
            model_name='species',
            name='variety_author',
        ),
    ]
