# Generated by Django 3.2 on 2025-03-22 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0009_auto_20250322_2314'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('category',)},
        ),
    ]
