# Generated by Django 3.2 on 2025-03-22 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0011_alter_species_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ('category__category', 'collective_species', 'plant'), 'permissions': (('can_check_nomenclature', 'can check nomenclature of a plant'),), 'verbose_name': 'plant', 'verbose_name_plural': 'plants'},
        ),
        migrations.AddField(
            model_name='species',
            name='plant',
            field=models.CharField(default='', max_length=100, verbose_name='plant'),
        ),
        migrations.AlterField(
            model_name='species',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='species.category', verbose_name='category'),
        ),
        migrations.AlterUniqueTogether(
            name='species',
            unique_together={('category', 'collective_species', 'plant', 'cultivar')},
        ),
        migrations.RemoveField(
            model_name='species',
            name='species',
        ),
    ]
