# Generated by Django 3.2 on 2025-03-25 06:48

import config_tables.admin
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='category')),
                ('full_name_generated', models.CharField(blank=True, max_length=350, verbose_name='full name')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('category',),
                'unique_together': {('category',)},
            },
            bases=(models.Model, config_tables.admin.Configurable),
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.CharField(default='', max_length=100, verbose_name='plant')),
                ('collective_species', models.CharField(blank=True, max_length=100, verbose_name='collective_species')),
                ('cultivar', models.CharField(blank=True, help_text='without quotation marks', max_length=200, verbose_name='cultivar / breed')),
                ('full_name_generated', models.CharField(blank=True, max_length=200, verbose_name='full name')),
                ('synonyme', models.TextField(blank=True, null=True, verbose_name='synonyms')),
                ('comment', models.TextField(blank=True, max_length=10000, null=True, verbose_name='comment')),
                ('picture', models.ImageField(blank=True, upload_to='pictures', verbose_name='picture')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'plant',
                'verbose_name_plural': 'plants',
                'ordering': ('category__category', 'collective_species', 'plant'),
                'permissions': (('can_check_nomenclature', 'can check nomenclature of a plant'),),
                'unique_together': {('category', 'collective_species', 'plant', 'cultivar')},
            },
            bases=(models.Model, config_tables.admin.Configurable),
        ),
    ]
