# Generated by Django 3.2 on 2025-03-27 21:42

import config_tables.admin
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_container', models.CharField(max_length=100, verbose_name='container')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='source')),
                ('collection_year', models.IntegerField(blank=True, verbose_name='collection_year')),
                ('creation_date', models.DateField(blank=True, null=True, verbose_name='creation_date')),
                ('is_alive_generated', models.BooleanField(default=False, editable=False, verbose_name='is alive')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.category', verbose_name='Category')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.plant', verbose_name='Plant')),
            ],
            options={
                'verbose_name': 'seed',
                'verbose_name_plural': 'seeds',
                'unique_together': {('plant', 'id_container', 'source', 'collection_year')},
            },
            bases=(models.Model, config_tables.admin.Configurable),
        ),
    ]
