# Generated by Django 3.2 on 2025-03-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeds',
            name='came_as_species',
            field=models.CharField(blank=True, max_length=100, verbose_name='came as species'),
        ),
        migrations.AddField(
            model_name='seeds',
            name='seed_available',
            field=models.BooleanField(blank=True, null=True, verbose_name='seed available'),
        ),
        migrations.AddField(
            model_name='seeds',
            name='seed_in_stock',
            field=models.BooleanField(blank=True, null=True, verbose_name='seed in stock'),
        ),
        migrations.AddField(
            model_name='seeds',
            name='species_checked_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='species checked by'),
        ),
    ]
