# Generated by Django 3.2 on 2025-03-31 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0002_auto_20250331_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seeds',
            name='came_as_species',
        ),
        migrations.RemoveField(
            model_name='seeds',
            name='category',
        ),
        migrations.RemoveField(
            model_name='seeds',
            name='seed_available',
        ),
        migrations.RemoveField(
            model_name='seeds',
            name='seed_in_stock',
        ),
        migrations.RemoveField(
            model_name='seeds',
            name='species_checked_by',
        ),
    ]
